files:
  - source: /en_UK/website/*.json
    translation: '%locale_with_underscore%/website'
  - source: en_UK/mods/gemsplusplus/*.json
    translation: '%locale_with_underscore%/mods/gemsplusplus'
  - source: en_UK/mods/lootbagmod/*.json
    translation: '%locale_with_underscore%/mods/lootbagmod'
  - source: en_UK/mods/magiceightcube/*.json
    translation: '%locale_with_underscore%/mods/magiceightcube'
